using ModelsClassLibrary.ModelsNS.UploadedFileNS;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModelsClassLibrary.ModelsNS.SharedNS.CounterNS
{

    /// <summary>
    /// This counts the clicks and sales amount generated by a certain Item
    /// One record is generated per click.
    /// </summary>
    public class Counter:CommonWithId
    {
        public Counter()
        {
            Name = Guid.NewGuid().ToString();
        }
        public override EnumLibrary.EnumNS.ClassesWithRightsENUM ClassNameForRights()
        {
            return EnumLibrary.EnumNS.ClassesWithRightsENUM.Counter;
        }
        public long Amount { get; set; }

        public CounterTypeENUM CounterTypeEnum { get; set; }

        
        public string UploadedFileId { get; set; }
        public UploadedFile UploadedFile { get; set; }


        public void AddClick(string uploadedFileId)
        {
            Amount = 1;
            CounterTypeEnum = CounterTypeENUM.Clicks;
            UploadedFileId = uploadedFileId;
        }
        
        /// <summary>
        /// This adds one number sale and credited to the uploaded file
        /// </summary>
        /// <param name="uploadedFileId"></param>
        public void AddSaleNoOf(string uploadedFileId)
        {
            Amount = 1;
            CounterTypeEnum = CounterTypeENUM.NoOfSales;
            UploadedFileId = uploadedFileId;
        }

        /// <summary>
        /// This adds sale amount and credited to the uploaded file
        /// </summary>
        /// <param name="uploadedFileId"></param>
        public void AddSaleAmount(string uploadedFileId, long amount)
        {
            Amount = amount;
            CounterTypeEnum = CounterTypeENUM.SaleAmount;
            UploadedFileId = uploadedFileId;
        }

        public override bool HideNameInView()
        {
            return true; ;
        }
    }
}
