// <auto-generated />
namespace DbContextLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _07082018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07082018));
        
        string IMigrationMetadata.Id
        {
            get { return "201808071107391_07-08-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
