// <auto-generated />
namespace DbContextLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _020520183 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_020520183));
        
        string IMigrationMetadata.Id
        {
            get { return "201806030920267_02-05-2018-3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
