// <auto-generated />
namespace DbContextLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _060920182 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_060920182));
        
        string IMigrationMetadata.Id
        {
            get { return "201809061255476_06-09-2018-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
