// <auto-generated />
namespace DbContextLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _21052018a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21052018a));
        
        string IMigrationMetadata.Id
        {
            get { return "201805211053073_21-05-2018a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
