// <auto-generated />
namespace DbContextLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _24102018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_24102018));
        
        string IMigrationMetadata.Id
        {
            get { return "201810240552386_24-10-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
